export const API_BASE = import.meta.env.VITE_API_URL || 'http://127.0.0.1:4178';
async function request(path, options = {}) {
  const response = await fetch(`${API_BASE}${path}`, { headers: { 'content-type': 'application/json', ...(options.headers || {}) }, ...options });
  const data = await response.json().catch(() => ({}));
  if (!response.ok) throw new Error(data.error || `请求失败 ${response.status}`);
  return data;
}
export const api = {
  summary: () => request('/api/workspaces/test-111/summary'),
  tasks: (query = '') => request(`/api/workspaces/test-111/tasks${query ? `?${query}` : ''}`),
  createTask: body => request('/api/workspaces/test-111/tasks', { method: 'POST', body: JSON.stringify(body) }),
  task: id => request(`/api/tasks/${id}`),
  updateTask: (id, body) => request(`/api/tasks/${id}`, { method: 'PATCH', body: JSON.stringify(body) }),
  taskMessages: id => request(`/api/tasks/${id}/messages`),
  addTaskMessage: (id, body) => request(`/api/tasks/${id}/messages`, { method: 'POST', body: JSON.stringify(body) }),
  taskAttachments: id => request(`/api/tasks/${id}/attachments`),
  uploadTaskAttachment: (id, body) => request(`/api/tasks/${id}/attachments`, { method:'POST', body:JSON.stringify(body) }),
  deleteTaskAttachment: id => request(`/api/task-attachments/${encodeURIComponent(id)}`, { method:'DELETE' }),
  downloadTaskAttachment: id => `${API_BASE}/api/task-attachments/${encodeURIComponent(id)}/download`,
  changeTaskState: (id, state) => request(`/api/tasks/${id}/state`, { method: 'POST', body: JSON.stringify({ state }) }),
  runtimes: () => request('/api/workspaces/test-111/runtimes'),
  models: (runtime = '', query = '') => request(`/api/workspaces/test-111/models?${new URLSearchParams({ ...(runtime ? { runtime } : {}), ...(query ? { q: query } : {}) }).toString()}`),
  skills: (filters = {}) => { const query = new URLSearchParams(Object.fromEntries(Object.entries(filters).filter(([,value]) => value))); const suffix = query.toString(); return request(`/api/workspaces/test-111/skills${suffix ? `?${suffix}` : ''}`); },
  skillSources: () => request('/api/workspaces/test-111/skill-sources'),
  createSkill: body => request('/api/workspaces/test-111/skills', { method: 'POST', body: JSON.stringify(body) }),
  importSkill: body => request('/api/workspaces/test-111/skills/import', { method: 'POST', body: JSON.stringify(body) }),
  copySkill: body => request('/api/workspaces/test-111/skills/copy', { method: 'POST', body: JSON.stringify(body) }),
  toggleSkill: (id, installed) => request(`/api/skills/${id}`, { method: 'PATCH', body: JSON.stringify({ installed }) }),
  uninstallSkill: id => request(`/api/skills/${id}/uninstall`, { method:'POST', body:'{}' }),
  skillVersions: id => request(`/api/skills/${id}/versions`),
  rollbackSkill: (id, versionId) => request(`/api/skills/${id}/rollback`, { method:'POST', body:JSON.stringify({ versionId }) }),
  documents: () => request('/api/workspaces/test-111/documents'),
  exportDocumentsGit: body => request('/api/workspaces/test-111/documents/git/export', { method:'POST', body:JSON.stringify(body || {}) }),
  importDocumentsGit: body => request('/api/workspaces/test-111/documents/git/import', { method:'POST', body:JSON.stringify(body || {}) }),
  documentTrash: () => request('/api/workspaces/test-111/documents/trash'),
  createDocument: body => request('/api/workspaces/test-111/documents', { method: 'POST', body: JSON.stringify(body) }),
  document: id => request(`/api/documents/${id}`),
  updateDocument: (id, body) => request(`/api/documents/${id}`, { method: 'PATCH', body: JSON.stringify(body) }),
  deleteDocument: id => request(`/api/documents/${id}`, { method: 'DELETE' }),
  restoreDocument: id => request(`/api/documents/${id}/restore`, { method:'POST', body:'{}' }),
  downloadDocument: id => `${API_BASE}/api/documents/${id}/download`,
  documentVersions: id => request(`/api/documents/${id}/versions`),
  restoreDocumentVersion: (id, version) => request(`/api/documents/${id}/versions/${version}/restore`, { method:'POST', body:'{}' }),
  automations: () => request('/api/workspaces/test-111/automations'),
  automationTemplates: () => request('/api/workspaces/test-111/automation-templates'),
  createAutomation: body => request('/api/workspaces/test-111/automations', { method: 'POST', body: JSON.stringify(body) }),
  automation: id => request(`/api/workspaces/test-111/automations/${id}`),
  updateAutomation: (id, body) => request(`/api/automations/${id}`, { method: 'PATCH', body: JSON.stringify(body) }),
  runAutomation: (id, mode = 'manual') => request(`/api/automations/${id}/run`, { method: 'POST', body: JSON.stringify({ mode }) }),
  automationRuns: id => request(`/api/automations/${id}/runs`),
  completeAutomationRun: (id, body) => request(`/api/automation-runs/${id}/result`, { method:'POST', body:JSON.stringify(body) }),
  deleteAutomation: id => request(`/api/automations/${id}`, { method: 'DELETE' }),
  members: () => request('/api/workspaces/test-111/members'),
  addMember: body => request('/api/workspaces/test-111/members', { method: 'POST', body: JSON.stringify(body) }),
  invitations: () => request('/api/workspaces/test-111/invitations'),
  createInvitation: body => request('/api/workspaces/test-111/invitations', { method: 'POST', body: JSON.stringify(body) }),
  resendInvitation: id => request(`/api/invitations/${id}/resend`, { method: 'POST', body: '{}' }),
  revokeInvitation: id => request(`/api/invitations/${id}/revoke`, { method: 'POST', body: '{}' }),
  lookupInvitation: code => request(`/api/invitations/lookup/${encodeURIComponent(code)}`),
  acceptInvitation: (code, body) => request(`/api/invitations/${encodeURIComponent(code)}/accept`, { method:'POST', body: JSON.stringify(body || {}) }),
  devices: () => request('/api/workspaces/test-111/devices'),
  addDevice: body => request('/api/workspaces/test-111/devices', { method: 'POST', body: JSON.stringify(body) }),
  updateDevice: (id, body) => request(`/api/devices/${encodeURIComponent(id)}`, { method:'PATCH', body:JSON.stringify(body) }),
  disableDevice: id => request(`/api/devices/${encodeURIComponent(id)}/disable`, { method:'POST', body:'{}' }),
  enableDevice: id => request(`/api/devices/${encodeURIComponent(id)}/enable`, { method:'POST', body:'{}' }),
  deleteDevice: id => request(`/api/devices/${encodeURIComponent(id)}`, { method:'DELETE' }),
  employees: () => request('/api/workspaces/test-111/employees'),
  createEmployee: body => request('/api/workspaces/test-111/employees', { method: 'POST', body: JSON.stringify(body) }),
  calendar: () => request('/api/workspaces/test-111/calendar'),
  calendarEvents: () => request('/api/workspaces/test-111/calendar/events'),
  createCalendarEvent: body => request('/api/workspaces/test-111/calendar/events', { method:'POST', body:JSON.stringify(body) }),
  calendarEvent: id => request(`/api/calendar-events/${encodeURIComponent(id)}`),
  updateCalendarEvent: (id, body) => request(`/api/calendar-events/${encodeURIComponent(id)}`, { method:'PATCH', body:JSON.stringify(body) }),
  deleteCalendarEvent: id => request(`/api/calendar-events/${encodeURIComponent(id)}`, { method:'DELETE' }),
  settings: () => request('/api/workspaces/test-111/settings'),
  permissions: () => request('/api/workspaces/test-111/permissions'),
  saveSettings: body => request('/api/workspaces/test-111/settings', { method: 'PATCH', body: JSON.stringify(body) }),
  apiKeys: () => request('/api/workspaces/test-111/api-keys'),
  createApiKey: body => request('/api/workspaces/test-111/api-keys', { method:'POST', body: JSON.stringify(body) }),
  revokeApiKey: id => request(`/api/api-keys/${id}/revoke`, { method:'POST', body:'{}' }),
  rotateApiKey: (id, body = {}) => request(`/api/api-keys/${id}/rotate`, { method:'POST', body:JSON.stringify(body) }),
  updateProfile: body => request('/api/workspaces/test-111/profile', { method:'PATCH', body:JSON.stringify(body) }),
  updatePreferences: body => request('/api/workspaces/test-111/preferences', { method:'PATCH', body:JSON.stringify(body) }),
  agents: () => request('/a2a/v1/agents'),
  notifications: (query = '') => request(`/api/workspaces/test-111/notifications${query ? `?${query}` : ''}`),
  markNotificationsRead: ids => request('/api/workspaces/test-111/notifications/read', { method:'POST', body:JSON.stringify(ids ? {ids} : {}) }),
  archiveNotification: (id, archived = true) => request(`/api/notifications/${id}/archive`, { method:'POST', body:JSON.stringify({archived}) }),
  conversations: () => request('/api/workspaces/test-111/conversations'),
  createConversation: body => request('/api/workspaces/test-111/conversations', { method:'POST', body:JSON.stringify(body) }),
  conversation: id => request(`/api/conversations/${id}`),
  addConversationMessage: (id, body) => request(`/api/conversations/${id}/messages`, { method:'POST', body:JSON.stringify(body) }),
  archiveConversation: (id, archived = true) => request(`/api/conversations/${id}/archive`, { method:'POST', body:JSON.stringify({archived}) })
};
